services:
  react-website:
    build:
      context: .
      args:
        - VITE_COMPANY_NAME=${VITE_COMPANY_NAME}
        - VITE_CONTACT_FORM_KEY=${VITE_CONTACT_FORM_KEY}
        - VITE_KLANT_ID=${VITE_KLANT_ID}
    container_name: website-lannie
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      - NODE_OPTIONS=--max-old-space-size=1800
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 2G
